{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMVJcUHY80OoPDzvrtKe39G",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/EEFrimpong/Course/blob/main/seir_simulation.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "R1IXVggcGcFM"
      },
      "outputs": [],
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"seir_simulations.py - SEIR Model with MPC Control\"\"\"\n",
        "\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy.integrate import odeint\n",
        "import pybounds\n",
        "\n",
        "############################################################################################\n",
        "# Set some global parameters\n",
        "############################################################################################\n",
        "mu = 0.000014        # Birth/Death rate per day (approximate)\n",
        "beta = 0.5           # Transmission rate\n",
        "sigma = 0.2          # Incubation rate (1/sigma = incubation period)\n",
        "gamma = 0.1          # Recovery rate (1/gamma = infectious period)\n",
        "N = 1000000          # Total population\n",
        "\n",
        "############################################################################################\n",
        "# Continuous time dynamics function\n",
        "############################################################################################\n",
        "class F(object):\n",
        "    def __init__(self):\n",
        "        pass\n",
        "\n",
        "    def f(self, x_vec, u_vec, mu=mu, beta=beta, sigma=sigma, gamma=gamma, N=N,\n",
        "          return_state_names=False):\n",
        "        \"\"\"\n",
        "        Continuous time dynamics function for SEIR model.\n",
        "\n",
        "        Parameters:\n",
        "        x_vec : array-like, shape (4,)\n",
        "            State vector [S, E, I, R]\n",
        "        u_vec : array-like, shape (3,)\n",
        "            Control vector [u1, u2, u3]\n",
        "            u1: transmission reduction (0=no reduction, 1=full reduction)\n",
        "            u2: vaccination rate\n",
        "            u3: treatment/isolation rate\n",
        "        mu : float\n",
        "            Birth/death rate per day\n",
        "        beta : float\n",
        "            Transmission rate\n",
        "        sigma : float\n",
        "            Incubation rate (1/sigma = incubation period)\n",
        "        gamma : float\n",
        "            Recovery rate (1/gamma = infectious period)\n",
        "        N : float\n",
        "            Total population\n",
        "\n",
        "        Returns:\n",
        "        x_dot : numpy array, shape (4,)\n",
        "            Time derivative of state vector\n",
        "        \"\"\"\n",
        "        if return_state_names:\n",
        "            return ['S', 'E', 'I', 'R']\n",
        "\n",
        "        # Extract state variables\n",
        "        S = x_vec[0]\n",
        "        E = x_vec[1]\n",
        "        I = x_vec[2]\n",
        "        R = x_vec[3]\n",
        "\n",
        "        # Extract control inputs\n",
        "        u1 = u_vec[0]  # transmission reduction (social distancing/masks)\n",
        "        u2 = u_vec[1]  # vaccination rate\n",
        "        u3 = u_vec[2]  # treatment/isolation rate\n",
        "\n",
        "        # SEIR dynamics\n",
        "        dS_dt = mu * N - beta * (1 - u1) * S * I / N - u2 * S - mu * S\n",
        "        dE_dt = beta * (1 - u1) * S * I / N - sigma * E - mu * E\n",
        "        dI_dt = sigma * E - (gamma + u3) * I - mu * I\n",
        "        dR_dt = (gamma + u3) * I + u2 * S - mu * R\n",
        "\n",
        "        x_dot_vec = np.array([dS_dt, dE_dt, dI_dt, dR_dt])\n",
        "\n",
        "        return x_dot_vec\n",
        "\n",
        "\n",
        "############################################################################################\n",
        "# Continuous time measurement functions\n",
        "############################################################################################\n",
        "class H(object):\n",
        "    def __init__(self, measurement_option):\n",
        "        self.measurement_option = measurement_option\n",
        "\n",
        "    def h(self, x_vec, u_vec, return_measurement_names=False):\n",
        "        h_func = self.__getattribute__(self.measurement_option)\n",
        "        return h_func(x_vec, u_vec, return_measurement_names=return_measurement_names)\n",
        "\n",
        "    def h_ir(self, x_vec, u_vec, return_measurement_names=False):\n",
        "        \"\"\"\n",
        "        Primary measurement: y = [I, R]^T (Infected and Recovered populations)\n",
        "        This is the measurement specified in your model\n",
        "        \"\"\"\n",
        "        if return_measurement_names:\n",
        "            return ['I_absolute', 'R_absolute']\n",
        "\n",
        "        # Extract state variables\n",
        "        I = x_vec[2]\n",
        "        R = x_vec[3]\n",
        "\n",
        "        # Measurements\n",
        "        y_vec = np.array([I, R])\n",
        "\n",
        "        return y_vec\n",
        "\n",
        "    def h_i(self, x_vec, u_vec, return_measurement_names=False):\n",
        "        \"\"\"\n",
        "        Alternative measurement 1: y = [I] (Infected population only)\n",
        "        \"\"\"\n",
        "        if return_measurement_names:\n",
        "            return ['I_absolute']\n",
        "\n",
        "        I = x_vec[2]\n",
        "        y_vec = np.array([I])\n",
        "\n",
        "        return y_vec\n",
        "\n",
        "    def h_ei(self, x_vec, u_vec, return_measurement_names=False):\n",
        "        \"\"\"\n",
        "        Alternative measurement 2: y = [E, I]^T (Exposed and Infected)\n",
        "        \"\"\"\n",
        "        if return_measurement_names:\n",
        "            return ['E_absolute', 'I_absolute']\n",
        "\n",
        "        E = x_vec[1]\n",
        "        I = x_vec[2]\n",
        "        y_vec = np.array([E, I])\n",
        "\n",
        "        return y_vec\n",
        "\n",
        "    def h_all(self, x_vec, u_vec, return_measurement_names=False):\n",
        "        \"\"\"\n",
        "        Alternative measurement 3: y = [S, E, I, R]^T (All compartments)\n",
        "        \"\"\"\n",
        "        if return_measurement_names:\n",
        "            return ['S_absolute', 'E_absolute', 'I_absolute', 'R_absolute']\n",
        "\n",
        "        S = x_vec[0]\n",
        "        E = x_vec[1]\n",
        "        I = x_vec[2]\n",
        "        R = x_vec[3]\n",
        "        y_vec = np.array([S, E, I, R])\n",
        "\n",
        "        return y_vec\n",
        "\n",
        "\n",
        "############################################################################################\n",
        "# SEIR simulation\n",
        "############################################################################################\n",
        "def simulate_seir(f, h, tsim_length=365, dt=1.0, measurement_names=None,\n",
        "                  setpoint=None, rterm_u1=1e-3, rterm_u2=1e-3, rterm_u3=1e-3, x0=None):\n",
        "    \"\"\"\n",
        "    Simulate SEIR disease model with MPC control\n",
        "\n",
        "    Parameters:\n",
        "    -----------\n",
        "    f : function\n",
        "        Dynamics function\n",
        "    h : function\n",
        "        Measurement function\n",
        "    tsim_length : float\n",
        "        Total simulation time in days\n",
        "    dt : float\n",
        "        Time step in days\n",
        "    measurement_names : list\n",
        "        Names of measurements\n",
        "    setpoint : dict\n",
        "        Desired trajectories for states\n",
        "    rterm_u1 : float\n",
        "        Control input penalty for transmission reduction\n",
        "    rterm_u2 : float\n",
        "        Control input penalty for vaccination\n",
        "    rterm_u3 : float\n",
        "        Control input penalty for treatment\n",
        "    x0 : array-like\n",
        "        Initial conditions\n",
        "\n",
        "    Returns:\n",
        "    --------\n",
        "    t_sim, x_sim, u_sim, y_sim, simulator\n",
        "    \"\"\"\n",
        "    # Set state and input names\n",
        "    state_names = f(None, None, return_state_names=True)\n",
        "    input_names = ['u1', 'u2', 'u3']  # transmission reduction, vaccination, treatment\n",
        "\n",
        "    # Choose the measurement function\n",
        "    if measurement_names is None:\n",
        "        try:\n",
        "            measurement_names = h(None, None, return_measurement_names=True)\n",
        "        except:\n",
        "            raise ValueError('Need to provide measurement_names as a list of strings')\n",
        "\n",
        "    # Initialize simulator\n",
        "    simulator = pybounds.Simulator(f, h, dt=dt, state_names=state_names,\n",
        "                                   input_names=input_names, measurement_names=measurement_names,\n",
        "                                   mpc_horizon=int(20/dt))\n",
        "\n",
        "    # Define the time horizon\n",
        "    tsim = np.arange(0, tsim_length, step=dt)\n",
        "    NA = np.zeros_like(tsim)\n",
        "\n",
        "    # Define default setpoint if not provided\n",
        "    if setpoint is None:\n",
        "        # Get initial conditions\n",
        "        if x0 is not None:\n",
        "            I_initial = x0[2]\n",
        "        else:\n",
        "            I_initial = 1000\n",
        "\n",
        "        # Infection setpoint: Decrease infections exponentially\n",
        "        I_target = 0.001 * N\n",
        "        I_setpoint = np.maximum(I_initial * np.exp(-tsim / 100), I_target)\n",
        "\n",
        "        # Exposed setpoint: Decrease exposed exponentially\n",
        "        E_target = 0.001 * N\n",
        "        E_setpoint = np.maximum(I_initial * np.exp(-tsim / 100), E_target)\n",
        "\n",
        "        setpoint = {\n",
        "            'S': NA,\n",
        "            'E': E_setpoint,\n",
        "            'I': I_setpoint,\n",
        "            'R': NA,\n",
        "        }\n",
        "\n",
        "    # Update the simulator set-point\n",
        "    simulator.update_dict(setpoint, name='setpoint')\n",
        "\n",
        "    # Define MPC cost function\n",
        "    cost_I = (simulator.model.x['I'] - simulator.model.tvp['I_set']) ** 2\n",
        "    cost_E = (simulator.model.x['E'] - simulator.model.tvp['E_set']) ** 2\n",
        "    cost = 100 * cost_I + 10 * cost_E\n",
        "\n",
        "    # Set cost function\n",
        "    simulator.mpc.set_objective(mterm=cost, lterm=cost)\n",
        "\n",
        "    # Set input penalty\n",
        "    simulator.mpc.set_rterm(u1=rterm_u1, u2=rterm_u2, u3=rterm_u3)\n",
        "\n",
        "    # Set bounds on states and controls\n",
        "    simulator.mpc.bounds['lower', '_x', 'S'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_x', 'S'] = N\n",
        "    simulator.mpc.bounds['lower', '_x', 'E'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_x', 'E'] = N\n",
        "    simulator.mpc.bounds['lower', '_x', 'I'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_x', 'I'] = N\n",
        "    simulator.mpc.bounds['lower', '_x', 'R'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_x', 'R'] = N\n",
        "\n",
        "    # Control bounds as specified\n",
        "    simulator.mpc.bounds['lower', '_u', 'u1'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_u', 'u1'] = 1.0\n",
        "    simulator.mpc.bounds['lower', '_u', 'u2'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_u', 'u2'] = 1.0\n",
        "    simulator.mpc.bounds['lower', '_u', 'u3'] = 0.0\n",
        "    simulator.mpc.bounds['upper', '_u', 'u3'] = 1.0\n",
        "\n",
        "    # Run simulation using MPC\n",
        "    t_sim, x_sim, u_sim, y_sim, = simulator.simulate(x0=x0, u=None, mpc=True, return_full_output=True)\n",
        "\n",
        "    return t_sim, x_sim, u_sim, y_sim, simulator\n",
        "\n",
        "\n",
        "############################################################################################\n",
        "# Example usage\n",
        "############################################################################################\n",
        "if __name__ == \"__main__\":\n",
        "    # Define initial conditions\n",
        "    # S, E, I, R\n",
        "    x0 = np.array([\n",
        "        990000,    # S - Susceptible (99% of population)\n",
        "        5000,      # E - Exposed\n",
        "        4000,      # I - Infected\n",
        "        1000       # R - Recovered\n",
        "    ])\n",
        "\n",
        "    # Create dynamics object\n",
        "    f_obj = F()\n",
        "\n",
        "    print(\"=\"*80)\n",
        "    print(\"TESTING SEIR MODEL WITH DIFFERENT MEASUREMENT OPTIONS\")\n",
        "    print(\"=\"*80)\n",
        "\n",
        "    # Test different measurement options\n",
        "    measurement_options = [\n",
        "        ('h_ir', 'Primary: I + R (as specified in your model)'),\n",
        "        ('h_i', 'Alternative 1: I only'),\n",
        "        ('h_ei', 'Alternative 2: E + I'),\n",
        "        ('h_all', 'Alternative 3: S + E + I + R (Full)')\n",
        "    ]\n",
        "\n",
        "    results = {}\n",
        "\n",
        "    for option_name, description in measurement_options:\n",
        "        print(f\"\\n{description}\")\n",
        "        print(\"-\" * 60)\n",
        "\n",
        "        h_obj = H(measurement_option=option_name)\n",
        "        measurement_names = h_obj.h(None, None, return_measurement_names=True)\n",
        "        print(f\"Measurements: {measurement_names}\")\n",
        "\n",
        "        try:\n",
        "            t_sim, x_sim, u_sim, y_sim, simulator = simulate_seir(\n",
        "                f_obj.f, h_obj.h, tsim_length=365, dt=1.0, x0=x0\n",
        "            )\n",
        "            results[option_name] = {\n",
        "                't': t_sim,\n",
        "                'x': x_sim,\n",
        "                'u': u_sim,\n",
        "                'y': y_sim,\n",
        "                'simulator': simulator,\n",
        "                'measurements': measurement_names\n",
        "            }\n",
        "            print(f\"✓ Simulation successful\")\n",
        "            print(f\"  Final S: {x_sim['S'][-1]:.0f}\")\n",
        "            print(f\"  Final E: {x_sim['E'][-1]:.0f}\")\n",
        "            print(f\"  Final I: {x_sim['I'][-1]:.0f}\")\n",
        "            print(f\"  Final R: {x_sim['R'][-1]:.0f}\")\n",
        "        except Exception as e:\n",
        "            print(f\"✗ Simulation failed: {str(e)}\")\n",
        "\n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(\"SEIR MODEL SIMULATION COMPLETE\")\n",
        "    print(\"=\"*80)\n",
        "    print(\"\\nModel parameters:\")\n",
        "    print(f\"  μ (birth/death rate): {mu}\")\n",
        "    print(f\"  β (transmission rate): {beta}\")\n",
        "    print(f\"  σ (incubation rate): {sigma} (incubation period: {1/sigma:.1f} days)\")\n",
        "    print(f\"  γ (recovery rate): {gamma} (infectious period: {1/gamma:.1f} days)\")\n",
        "    print(f\"  N (population): {N}\")\n",
        "    print(\"\\nControl inputs:\")\n",
        "    print(\"  u1: Transmission reduction (social distancing/masks), 0 ≤ u1 ≤ 1\")\n",
        "    print(\"  u2: Vaccination rate, 0 ≤ u2 ≤ 1\")\n",
        "    print(\"  u3: Treatment/isolation rate, 0 ≤ u3 ≤ 1\")\n",
        "    print(\"=\"*80)"
      ]
    }
  ]
}
